nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600
